// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("MeanDiff")>]
[<assembly: AssemblyProductAttribute("MeanDiff")>]
[<assembly: AssemblyDescriptionAttribute("MeanDiff: BBIR testing tool")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: GuidAttribute("346faf23-b624-4861-ae72-0efb43ad4b68")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (c) KAIST, since 2017")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MeanDiff"
    let [<Literal>] AssemblyProduct = "MeanDiff"
    let [<Literal>] AssemblyDescription = "MeanDiff: BBIR testing tool"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] Guid = "346faf23-b624-4861-ae72-0efb43ad4b68"
    let [<Literal>] AssemblyCopyright = "Copyright (c) KAIST, since 2017"
